language: objective-c
osx_image: xcode11.5

script:
  - xcodebuild -project Dysprosium.xcodeproj -scheme Dysprosium -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' clean build test
